[custom]
;自定义链接
ruleset=全球直连,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/DIRECT/CLOUDFLARE.LIST
ruleset=全球直连,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/DIRECT/DIRECT.LIST
ruleset=全球直连,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/DIRECT/APPLE.LIST
ruleset=全球直连,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/DIRECT/MICROSOFT.LIST
ruleset=全球拦截,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/REJECT/AD.LIST
;中国媒体列表
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
;Unbreak 白名单 不应该被广告链接的网站
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;国内常见
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;中国云服务商ip端
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;下载
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;本地/局域网地址
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;直连进程名称
ruleset=全球直连,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/DIRECT/PROCESS.LIST
ruleset=全球直连,[]GEOIP,LAN
ruleset=全球直连,[]GEOIP,CN
;代理
ruleset=节点选择,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/PROXY/PROXY.LIST
;代理进程名称
ruleset=节点选择,https://raw.githubusercontent.com/han1182/ProxyRules/master/list/PROXY/PROCESS.LIST
;__________________________________________________________________________________________________________________________________________________________
custom_proxy_group=节点选择`select`[]自动选择`[]手动切换
custom_proxy_group=自动选择`url-test`[]香港`[]日本`[]美国`[]台湾`[]韩国`[]新加坡`[]加拿大`[]西欧南非
custom_proxy_group=手动切换`select`[]干净节点`[]香港`[]美国`[]新加坡`[]日本`[]韩国`[]台湾`[]加拿大`[]西欧南非
custom_proxy_group=全球直连`select`[]DIRECT`[]节点选择
custom_proxy_group=全球拦截`select`[]REJECT
custom_proxy_group=漏网之鱼`select`[]自动选择`[]DIRECT
;（CloudFlare访问不稳定的特殊网站 例：Pixiv）
;地区分组
custom_proxy_group=香港`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=美国`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=台湾`url-test`(台|新北|彰化|TW|Taiwan|TPE|KHH)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=韩国`url-test`(KR|Korea|KOR|Seoul|首尔|春川|韩|韓|ICN)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=新加坡`url-test`(新加坡|坡|狮城|SG|Singapore|SIN)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=加拿大`url-test`(🇨🇦|CA|Canada|加拿大|渥太华|多伦多|温哥华|艾德蒙顿|CAN)`[]REJECT`http://www.gstatic.com/generate_204`300
custom_proxy_group=西欧南非`url-test`(俄罗斯|🇷🇺|莫斯科|新西伯利亚|英国|🇬🇧|伦敦|法国|🇫🇷|阿根廷|🇦🇷|德国|土耳其|🇹🇷|荷兰|🇳🇱|西班牙|乌克兰|希腊|比利时|意大利|卢森堡|立陶宛|瑞典|奥地利|波兰|塞尔维亚|爱沙尼亚|爱尔兰|罗马尼亚|南非|🇿🇦)`[]REJECT`http://www.gstatic.com/generate_204`300
enable_rule_generator=true
overwrite_original_rules=true
